/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AiseraUniversalWidget {
    }
}
declare global {
    interface HTMLAiseraUniversalWidgetElement extends Components.AiseraUniversalWidget, HTMLStencilElement {
    }
    var HTMLAiseraUniversalWidgetElement: {
        prototype: HTMLAiseraUniversalWidgetElement;
        new (): HTMLAiseraUniversalWidgetElement;
    };
    interface HTMLElementTagNameMap {
        "aisera-universal-widget": HTMLAiseraUniversalWidgetElement;
    }
}
declare namespace LocalJSX {
    interface AiseraUniversalWidget {
    }
    interface IntrinsicElements {
        "aisera-universal-widget": AiseraUniversalWidget;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "aisera-universal-widget": LocalJSX.AiseraUniversalWidget & JSXBase.HTMLAttributes<HTMLAiseraUniversalWidgetElement>;
        }
    }
}
