name: Build and Deploy Zendesk App

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for (e.g., zendesk)'
        required: true
        default: 'zendesk'

jobs:
  build-and-deploy-zendesk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Templates Repo
        uses: actions/checkout@v4
        with:
          repository: soumyabera-aisera/widget-templates
          path: templates-repo

      - name: Assemble Minimal App for Deployment
        run: |
          # 1. Create a clean app directory
          mkdir -p ./app_dist/assets

          # 2. Copy the essential files for a basic Zendesk app
          cp ./templates-repo/zendesk-template/manifest.json ./app_dist/
          cp -r ./templates-repo/zendesk-template/translations ./app_dist/
          cp ./templates-repo/zendesk-template/assets/logo.png ./app_dist/assets/
          cp ./templates-repo/zendesk-template/assets/logo-small.png ./app_dist/assets/
          cp ./templates-repo/zendesk-template/index.html ./app_dist/assets/

          # 3. (FIX) Copy the ZCLI config file containing the app_id
          cp ./templates-repo/zendesk-template/zcli.apps.config.json ./app_dist/

      - name: Install ZCLI
        run: npm install @zendesk/zcli -g

      - name: Validate, Package, and Deploy to Zendesk
        env:
          ZENDESK_SUBDOMAIN: ${{ secrets.ZENDESK_SUBDOMAIN }}
          ZENDESK_EMAIL: ${{ secrets.ZENDESK_EMAIL }}
          ZENDESK_API_TOKEN: ${{ secrets.ZENDESK_API_TOKEN }}
        run: zcli apps:update ./app_dist