# .github/workflows/build-package.yml

name: Build Widget Package

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for (e.g., zendesk)'
        required: true
        default: 'zendesk'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Widget Repo
        uses: actions/checkout@v4
        with:
          path: widget-repo

      - name: Checkout Templates Repo
        uses: actions/checkout@v4
        with:
          repository: soumyabera-aisera/widget-templates
          path: templates-repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Universal Widget
        run: |
          cd widget-repo/universal-widget
          npm install
          npx stencil build --prod

      # (CHANGED) Assemble the app using the correct 'dist' production output
      - name: Assemble Zendesk App
        if: ${{ github.event.inputs.platform == 'zendesk' }}
        run: |
          # 1. Create the final directory structure
          mkdir -p build-output/app/assets/dist

          # 2. Copy manifest into the 'app' folder
          cp templates-repo/zendesk-template/manifest.json build-output/app/

          # 3. Copy index.html into the 'assets' folder
          cp templates-repo/zendesk-template/index.html build-output/app/assets/

          # 4. Copy the entire 'dist' folder (production output) into assets
          cp -r widget-repo/universal-widget/dist/* build-output/app/assets/dist/

      - name: Zip the package
        if: ${{ github.event.inputs.platform == 'zendesk' }}
        run: |
          (cd build-output/app && zip -r ../../app.zip .)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zendesk-app
          path: app.zip