name: Build Widget Package

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for (e.g., zendesk)'
        required: true
        default: 'zendesk'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Widget Repo
        uses: actions/checkout@v4
        with:
          path: widget-repo

      - name: Checkout Templates Repo
        uses: actions/checkout@v4
        with:
          repository: soumyabera-aisera/widget-templates
          path: templates-repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Universal Widget
        run: |
          cd widget-repo/universal-widget
          npm install
          npx stencil build

      - name: Assemble Zendesk App
        run: |
          # 1. Create the final directory structure based on the working example
          mkdir -p build-output/app/assets/build

          # 2. Copy manifest into the 'app' folder
          cp templates-repo/zendesk-template/manifest.json build-output/app/

          # 3. Copy our custom index.html into the 'app/assets/build' folder
          cp templates-repo/zendesk-template/index.html build-output/app/assets/build/

          # 4. Copy the component's JS file from the correct debugged path
          cp widget-repo/universal-widget/dist/components/aisera-universal-widget.js build-output/app/assets/build/

      - name: Zip the package
        run: |
          # Zip the contents of the 'app' folder to create a clean root
          (cd build-output/app && zip -r ../../app.zip .)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zendesk-app
          path: app.zip