# .github/workflows/build-package.yml

name: Build Widget Package

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for (e.g., zendesk)'
        required: true
        default: 'zendesk'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Widget Repo
        uses: actions/checkout@v4
        with:
          path: widget-repo

      - name: Checkout Templates Repo
        uses: actions/checkout@v4
        with:
          repository: soumyabera-aisera/widget-templates
          path: templates-repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Universal Widget
        run: |
          cd widget-repo/universal-widget
          npm install
          npm run build

      - name: Assemble Zendesk App
        if: ${{ github.event.inputs.platform == 'zendesk' }}
        run: |
          mkdir -p build-output/assets/build
          cp templates-repo/zendesk-template/manifest.json build-output/
          cp templates-repo/zendesk-template/index.html build-output/assets/
          cp -r widget-repo/universal-widget/www/build/* build-output/assets/build/

      # --- START OF DEBUGGING STEPS ---
      - name: Debug File Structure
        if: ${{ github.event.inputs.platform == 'zendesk' }}
        run: |
          echo "--- Listing contents of build-output directory ---"
          ls -R build-output

      - name: Debug File Contents
        if: ${{ github.event.inputs.platform == 'zendesk' }}
        run: |
          echo "--- Printing content of manifest.json ---"
          cat build-output/manifest.json
          echo "--- Printing content of assets/index.html ---"
          cat build-output/assets/index.html

      - name: Zip the package
        if: ${{ github.event.inputs.platform == 'zendesk' }}
        run: |
          (cd build-output && zip -r ../app.zip .)

      - name: Inspect Final Zip Archive
        if: ${{ github.event.inputs.platform == 'zendesk' }}
        run: |
          echo "--- Inspecting contents of final app.zip ---"
          unzip -l app.zip
      # --- END OF DEBUGGING STEPS ---

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zendesk-app
          path: app.zip