# .github/workflows/build-package.yml

name: Build Widget Package

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for (e.g., zendesk)'
        required: true
        default: 'zendesk'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Widget Repo
        uses: actions/checkout@v4
        with:
          path: widget-repo

      - name: Checkout Templates Repo
        uses: actions/checkout@v4
        with:
          repository: soumyabera-aisera/widget-templates
          path: templates-repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Universal Widget
        run: |
          cd widget-repo/universal-widget
          npm install
          npm run build

      # (CHANGED) Assemble the app using our custom index.html
      - name: Assemble Zendesk App
        if: ${{ github.event.inputs.platform == 'zendesk' }}
        run: |
          # 1. Create the final directory structure
          mkdir -p build-output/assets/build

          # 2. Copy the manifest and our new index.html from the template
          cp templates-repo/zendesk-template/manifest.json build-output/
          cp templates-repo/zendesk-template/index.html build-output/assets/

          # 3. Copy ONLY the compiled JavaScript 'build' folder into assets
          cp -r widget-repo/universal-widget/www/build/* build-output/assets/build/

      - name: Zip the package
        if: ${{ github.event.inputs.platform == 'zendesk' }}
        run: |
          (cd build-output && zip -r ../app.zip .)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zendesk-app
          path: app.zip