name: Build Widget Package

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform to build for (e.g., zendesk)'
        required: true
        default: 'zendesk'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Widget Repo
        uses: actions/checkout@v4
        with:
          path: widget-repo

      - name: Checkout Templates Repo
        uses: actions/checkout@v4
        with:
          repository: soumyabera-aisera/widget-templates
          path: templates-repo

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Build Universal Widget
        run: |
          cd widget-repo/universal-widget
          npm install
          # We no longer need the --prod flag as the config forces the right output
          npx stencil build

      - name: Assemble Zendesk App
        run: |
          # 1. Create the final directory structure
          mkdir -p build-output/app/assets/build

          # 2. Copy manifest and index.html from templates
          cp templates-repo/zendesk-template/manifest.json build-output/app/
          cp templates-repo/zendesk-template/index.html build-output/app/assets/

          # 3. Copy the single, bundled JS file into the 'build' folder
          # The output is now in the 'dist' folder, not 'dist/components'
          cp widget-repo/universal-widget/dist/universal-widget.js build-output/app/assets/build/

      - name: Zip the package
        run: |
          (cd build-output/app && zip -r ../../app.zip .)

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: zendesk-app
          path: app.zip